#!/usr/bin/env sh

echo -e "\n\033[1;36m[i] Running pre-commit checks...\033[0m\n"

staged=$(git diff --cached --diff-filter=d --name-only)
files=()
exit_code=$?

if [[ -n "$staged" ]]; then
  if [[ $exit_code -eq 0 ]]; then
    files=$(grep -E '\.(astro|ts|tsx)$' <<< "$staged" || true)

    if [ -n "$files" ]; then
      npm run check
      exit_code=$?
    fi
  fi

  if [[ $exit_code -eq 0 ]]; then
    files=$(grep -E '\.(astro|js|scss|ts|tsx)$' <<< "$staged" || true)

    if [ -n "$files" ]; then
      npm run lint-staged
      exit_code=$?
    fi
  fi

  if [[ -n "$files" ]]; then
    if [[ $exit_code -eq 0 ]]; then
      echo -e "\n\033[1;32m[√] Changes look good - no errors have been found.\033[0m\n"
      exit 0
    else
      echo -e "\n\033[1;31m[X] Errors have been found - fix them and try again.\033[0m\n"
      exit $exit_code
    fi
  fi
fi
